browser=chrome
baseUrl=https://www.saucedemo.com
timeout=10
headless=false
password=secret_sauce
standardUser=standard_user
lockedOutUser=locked_out_user
problemUser=problem_user
invalidUser=invalid_user
firstName=Shop
lastName=Bot
postalCode=560001
